[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_amm = "JBX3RkX7U3WJ3u3q4vrrqiMzh9weSR3YekhwZX4b4HV4"
[programs.devnet]
solana_amm = "JBX3RkX7U3WJ3u3q4vrrqiMzh9weSR3YekhwZX4b4HV4"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "~/.config/solana/id.json"
cluster = "https://api.devnet.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
